languages/fr_lang.lua
Added French language for vorp_inventory-lua
=> Add French translation

vorpInventoryApi.lua
What this PR adds:
1. Added fix for canCarryItem
=> canCarryItem Fix

fxmanifest.lua, languages/de_lang.lua, languages/en_lang.lua, languages/es_lang.lua, languages/fr_lang.lua, languages/no_lang.lua, languages/pt_lang.lua, version
**The Issue This Resolves:** 
CodingCobra mentioned that a couple of language calls were missing and spitting out an error.
https://prnt.sc/svGajKSsE30H
**What this changes:**
- Adds missing language variables from the language configs.
- Updated some non-translated locales
_Warning: I translated to the best of my knowledge, and with help of Google Translate. Please correct anything that is wrong._
=> Language updates and fix

client/controllers/NUIController.lua, client/services/NUIService.lua, html/css/ui.min.css, html/ui.html, languages/de_lang.lua, languages/en_lang.lua, languages/es_lang.lua, languages/fr_lang.lua, languages/no_lang.lua, languages/pt_lang.lua, server/services/inventoryService.lua
1. New UI transaction loader for giving an item to another player. It disables the cursor and displays a loading modal, preventing players from exploiting items during the "giving item" transaction. [Issue 34](https://github.com/VORPCORE/vorp_inventory-lua/issues/34)
=> Transaction loader to safeguard giving items to other players

client/controllers/NUIController.lua
What this changes:
1. Bugfix for [Issue 39](https://github.com/VORPCORE/vorp_inventory-lua/issues/39)
=> New Event Bugfix

README.md, client/controllers/PickupsController.lua, client/models/ItemClass.lua, client/models/Pickup.lua, client/models/WeaponClass.lua, client/services/InventoryApiService.lua, client/services/InventoryService.lua, client/services/NUIService.lua, client/services/PickupsService.lua, client/services/UtilityService.lua, config.lua, html/css/ui.min.css, html/js/config.js, html/ui.html, languages/en_lang.lua, server/controllers/inventoryController.lua, server/models/ItemClass.lua, server/models/WeaponClass.lua, server/services/inventoryApiService.lua, server/services/inventoryService.lua, server/services/itemsDatabase.lua, sql/database.sql
descriptions of items are in DB
desc of weapons is in config.lua
desc of dollars and gold are in html
for use gold like dollars go in config.lua and config.js and put UseGoldItem = true
=> new pr for descriptions and gold use

config.lua, languages/de_lang.lua
duplicate removed
added missing
corrections and adjustments
=> Corrections

html/ui.html
1. Bugfix for [Banking Issue 5](https://github.com/VORPCORE/vorp_banking/issues/5)
=> Inner HTML capacity bugfix

ammoDB.sql, client/client.lua, client/controllers/NUIController.lua, client/controllers/PickupsController.lua, client/models/WeaponClass.lua, client/services/InventoryApiService.lua, client/services/InventoryService.lua, client/services/NUIService.lua, config.lua, fxmanifest.lua, html/ui.html, server/controllers/inventoryApiController.lua, server/services/inventoryApiService.lua, vorpInventoryApi.lua
Ammo will no longer go into your weapon. it will not go into your gunbelt
1- no more infinite throwables
2- no more ammo dupe using dual wielding
3- you can now pick up arrows u shoot or bollas you throw
4- all guns of the same type now share the same ammo pool
Note:
with throwables and bows. your last when you are on 1 ammo it will be considered as 0 if you relog.
make sure u update ur db withj ammoDB.sql
=> ammo overhaul update

html/css/ui.min.css
=> added proper word break to description

server/services/inventoryApiService.lua, server/services/inventoryService.lua
Here is a little fix that check if the item exist in db before precessing the action.
This check is done in every function of the inventory and the API on server Side.
I hope this will fix the strange issue when a svItem lose his methods from the Item Class.
=> Check for existing item in DB

client/services/NUIService.lua, config.lua, html/js/script.js
- You can now turn of the auto focus for inventory searching on keypress. `InventorySearchAutoFocus = true, -- Search autoofocuses when you type`
=> Search AutoFocus Config Toggle

server/services/dbUpdater.lua
- Adds new metadata sql to the database auto updater.
=> Adding metadata sql to dbupdater

server/services/dbUpdater.lua
- Fixed DBUpdater. [Issue 87](https://github.com/VORPCORE/vorp_inventory-lua/issues/87)
=> Bugfix: DBUpdater RaceCase

html/js/invScript.js, html/js/secondaryInvScript.js
Don't display description if there is none.
=> Don't display description if there is none.

html/js/invScript.js
Money is now displayed in inventory as specified in languages ​​(dollar,euro,peso) whatever ;)
=> Fix money label in inventory

server/services/inventoryApiService.lua
Teranry operation to default set a boolean value is not the same wether the default value is true or false
=> Fix bad lua Logic on ternary operation

server/controllers/inventoryApiController.lua, server/services/DbService.lua, server/services/inventoryApiService.lua, vorpInventoryApi.lua
Aloso Adding boolean return value for add/sub item API
=> Fix Uppercase wepaon name for custom inv set limit.

client/services/InventoryService.lua, client/services/UtilityService.lua, html/js/invScript.js, html/js/secondaryInvScript.js, server/services/inventoryApiService.lua, server/services/inventoryService.lua, server/services/itemsDatabase.lua, shared/models/ItemClass.lua
That should fix item description not showing on the ui.
https://i.imgur.com/WONVJaZ.png
https://i.imgur.com/Ue6P329.png
=> Item description

server/server.lua
bad argument #1 to 'sub' (string expected, got nil)
=> Fix Discord ID spamming

client/services/NUIService.lua, config.lua, html/js/config.js, html/js/invScript.js, html/js/script.js
**What this changes:**
- New ` DoubleClickToUse = true` config toggle. If toggled to false, items in inventory will right click then left click "use"
=> Adding rightclicktouse config toggle

config.lua, server/services/inventoryService.lua
Timer is at top of server, config line has been added,
=> Add Config.NewPlayers

html/css/ui.min.css, html/js/script.js, html/js/utils.js, html/ui.html
**What this changes:**
- Dup fix for giving an item.
=> Dup fix for giving an item.

client/services/NUIService.lua, client/services/NUIValidator.lua, config.lua, fxmanifest.lua, html/js/nui.js, html/js/utils.js, html/ui.html, server/server.lua, shared/services/Regex.js
- Dup fix for net calls
- Webhook for players attempting the netdup
=> NetDup Fix

config.lua
added some missing ammos for the hatchets
=> adding missing hatchet ammo

html/js/utils.js
Second inventory had a fixed placeholder on 'Search'. With this change the second inventory will now also use the language file for easy translations!
=> Update utils.js - Added 2nd inventory language link

languages/language.lua
Added Missing Translations for Italian Update language.lua
=> Missing Translations :( - Update language.lua

server/services/inventoryApiService.lua
An error what ocurred when Config.Debug is set to true.
=> Error when Config.Debug is True.

config/config.lua, config/logs.lua, fxmanifest.lua, server/server.lua, server/services/UtiliyService.lua, server/services/inventoryApiService.lua, server/services/inventoryService.lua
i'm not sure if this is something you wanted to do but if not feel free to close :smile: 
just thought the main config file was getting a bit full lol
=> move all log/webhooks configs and add color for each type of log 

server/services/inventoryApiService.lua, server/types/types.lua
You did a very good job by documenting every API routes !
Some mistakes were in the comments, so I fixed them.
=> Fix API types doc

client/controllers/NUIController.lua, client/services/NUIService.lua, html/js/script.js
> [!IMPORTANT]
>
This fix problem if player disconnect, close inv.
This fix problem if player disconnect, close inv.
This fix problem if player disconnect, close inv.
=> chore(client) if player is offline close inv.

html/js/script.js
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
display #rol on UI
so you can see the Rol Tokens in the Inventory UI
Rol Token in inventory UI 
- [x ] Tested with latest vorp scripts
- [x ] Tested with latest artifacts
=> Displaying #rol on inventory UI

html/js/secondaryInvScript.js
> [!IMPORTANT]
>
For example, for lumberjacks or mine workers who move a lot of items back and forth between player inventory and storage, it is more convenient if they can move a whole stack quickly.
The changes have the following effect, here are 2 examples
Example 1: If you have ONE piece of iron in your inventory and want to move it, there is no input field because you only have ONE piece.
Example 2: You have 50 …
=> Allow move all items as an option to custom inventories  when a key is pressed

README.md
> [!IMPORTANT]
>
Cleaned up and fixed grammar, spelling and format for README
Cleaned up and fixed grammar, spelling and format for README
Cleaned up and fixed grammar, spelling and format for README
Cleaned up and fixed grammar, spelling and format for README
=> Cleaned up and fixed grammar, spelling and format for README

client/services/PickupsService.lua
=> Chore: missing Concatenator

client/services/PickupsService.lua
=> Chore: fix Sting

client/services/NUIService.lua, config/config.lua
> [!IMPORTANT]
>
“Config.Filter” has been added. Additions were made to "Config.noSerialNumber" and some cleaned up, fixed grammar, spelling corrections.
“Config.Filter” has been added. Additions were made to Config.noSerialNumber. With `Config.Filter` they can change the filter from one place when the inventory is opened
“Config.Filter” has been added. Additions were made to Config.noSerialNumber. With `Config.Filter` …
=> “Config.Filter” has been added. Additions were made to "Config.noSerialNumber"

README.md
> [!IMPORTANT]
>
Updated README according to the new updates
=> Updated README according to the new updates

client/models/WeaponClass.lua, client/services/ammoService.lua, config/ammo.lua, config/config.lua
You need also add ammo item in your weapon script to fill the WEAPON_MOONSHINEJUG_MP.
for vorp_weaponsv2 add next code to ammo.lua
```lua
["MoonshineJug"] = {
["Moonshine Liters"] = {
key = "AMMO_MOONSHINEJUG_MP",-- DO NOT CHANGE THESE
item = "ammomoonshine",
playeritem = {"WEAPON_MOONSHINEJUG_MP"},
letcraft = false, -- show in crafting u can toggle this to false if you want to make this weapon sellable but not craftable
craftcost = 0,
jobonly = false, -- turn this to true if you want crafting this weapon to only be allowed for a certain job
jobs = {"police","gunsmith","rguns"}, -- jobs that can craft this weapon is job only is true
maxammo = 100, -- max ammo allowed by game
guncheck = 0  ,-- DO NOT CHANGE THESE
qt = 10, -- number of bullets in box
materials = {
item1 = {name = "iron", …
```
=> Added support for WEAPON_MOONSHINEJUG_MP

server/services/inventoryService.lua
> [!IMPORTANT]
>
- [ x ] Bug fix (non-breaking change which fixes an issue)
=> chore fix Gold pickup and drop logs

client/services/NUIService.lua, languages/language.lua
=> Chore: add missing langs and fix spelling

server/services/inventoryApiService.lua
> [!IMPORTANT]
>
This change will make the getCustomInventorySlots export to work.
This change will help peoples who want to use export for getCustomInventorySlots to work, since right now is not working because there is not export for this.
This change will not have any negative impact to framework or its users
I dont have any extra notes!
=> feat(server): add getCustomInventorySlots export

client/services/NUIService.lua, config/config.lua
> [!IMPORTANT]
>
Item spam delay time added to the config file.
=> Item spam delay time added to the config file.

server/respawn.lua
> [!IMPORTANT]
>
To fix an issue reported by someone that had respawned and lost items we had defined within itemWhiteList within the config.
To stop others from encounter the same issues we have and had to do extra work to return lost items.
n/a
=> Fix for items defined within itemWhiteList not being kept after choosing to respawn with UseClearAll enabled.
