client/controllers/NUIController.lua
vorpInventoryApi.lua

**What this PR adds:**
> I noticed openInv was halfway integrated, so completing that connection.
1. You can now open Inventory programmatically through the InventoryAPI
2. NuiController (ClientNetEvent) for opening Inventory was added.

Open Inventory with Inv API and NUIController

---

fxmanifest.lua
version

I just realized we did not bump the version with the last set of updates. Bumping to 1.0.5

1.0.5 Version Bump

---

client/services/NUIService.lua
fxmanifest.lua
html/css/ui.min.css
html/ui.html
version

**What this PR adds:**
1. Client support for inventory capacity for secondary inventories (Backwards compatible, capacity will not display if not used)
[Trello Task](https://trello.com/c/88eIeusw/8-add-inventory-capacity-to-horse-housing-inventory-ui-and-api)
**Caution**
_This has only been tested on a 2k monitor (other resolutions need to be tested/added)_

Capacity support for secondary inventory

---

fxmanifest.lua
server/controllers/inventoryApiController.lua
server/services/inventoryApiService.lua
version
vorpInventoryApi.lua

1. Bugfix: canCarryItem was erroring with invalid items.
2. Server API Feature:  `getItem` added!
3. Server API Feature:  `getDBItem` added!
4. Server API Enhancement: `canCarryWeapons` added to API, was only available as serverEvent prior.
**_Server API Usage:_**
- **getItem**
This will let you see a single item in a player's inventory
```lua 
local item = VorpInv.getItem(_source, item)
```
- **getDBItem**
This lets you see a single item from the Database
```lua 
local item = VorpInv.getDBItem(_source, item)
```
- **canCarryWeapons** 
```lua 
VorpInv.canCarryWeapons(_source, player, amount, function (result)
local cancarry = result
end)
```

New API functions and bug fixes

---

client/services/PickupsService.lua
config.lua
server/controllers/inventoryController.lua
server/services/inventoryService.lua

if activated, on DropOnRespawn only removes a configurable percentage of the money that the player has with him

Add DropOnRespawn only part of money with configurable percentage 

---

server/services/inventoryApiService.lua

Not sure if it's a proper fix. I've done superficial reverse engineering and that's what I came up with. It works, but I'm not sure about its reliability.
The problem before the fix:
https://streamable.com/pmk6df
What was causing the problem:
Basically, the inventory was sent two times in two different formats. The fact that the problem looked so "random" was caused by something like a race condition, the last query to finish was the inventory that would get loaded.
After the patch:
The script now works for both shared and private custom inventories, you can transfer items without problems. Looks like it's fixed, but again - I'm not sure if this fix could lead to other bugs which I hadn't considered.

Fix(?) for shared custom inventories

---

server/services/inventoryApiService.lua
server/services/inventoryService.lua
shared/models/ItemClass.lua
vorpInventoryApi.lua

Added a parameter for the registerInventory API method which allows ignoring the item stack limit on the target custom inventory.
Example of actual behavior:
Users can carry a max of 30 rocks, deposit can't have more than 30 rocks even though the deposit limit is, let's say, 1000.
Example of wanted behavior:
User can carry a max of 30 rocks, deposit can have more than 30 rocks until it reaches the inventory maximum along with other items.
The `ignoreItemStackLimit` parameter is set to false by default.

Added ignoreStackLimit parameter and Fix for weapon transfer

---

server/services/inventoryService.lua

**How the bug occurs and how to replicate:**
- CustomInventory: 1x "Item A", this item has a limit of 25 units in the user inventory
- User takes 25x "Item A"
- The subItem function will not allow subtracting this quantity, since it's above the item count
- However, this is not blocking the execution of the function, which leads then to still call addItems
- The user now has 25x "Item A"
- CustomInventory has still 1x "Item A" since, of course, it hasn't subtracted items.
**The fix:**
The fix was pretty straightforward, it was just a matter of checking whether the amount requested wasn't higher than the amount available.

[FIX] Item duplication when taking items from a custom inventory

---

server/services/inventoryApiService.lua
server/services/inventoryService.lua
vorpInventoryApi.lua

Adding a whitelistItems paramater to the registerInventory API function.
Default value is False.
When this parameter is set to True, only the limited items will be taken into account when moving items to inventory.
Need Some testing.

Add whitelist mode for custom inventories

---

vorpInventoryApi.lua

+ For example the function dbQuery use a promise which gets resolved when the query is done and the callback is called. Until the promise is resolved, the function will wait via Citizen.Await. The advantage of Promises with Citizen.Await is that you don't have to wait the minimum time x milliseconds like in a while loop. Before you had to wait at least 500ms per call of the old version of canCarryItem. If you made several calls of the old version of canCarryItem, then correspondingly longer. Although the queries were finished faster. With the combination of Promises and Citizen.Await this is now obsolete.  Clear advantage: better performance and faster responses.
+ Update all other functions with that design that have return values.
+ Remove unused variables 'metadata' in …

Use promises instead of wait loops

---

client/services/NUIService.lua
html/css/ui.min.css
html/js/utils.js
server/services/inventoryService.lua

Too tired, so I will test the giveweapon transaction loading modal in the morning.  
**What this changed**
-  🆕 Search bar for secondary inventories. They can get pretty long (this includes banks, storages, etc), so a search we think was much needed.
- 🆕 Transaction loader (same loading modal you get when giving items) will now apply to giving weapons as well
- Minor bug fix.

Search for secondary Inventory + Transaction loader added to giveWeapons

---

html/js/script.js

Bug: Search autofocus would override when clicking into the new secondary inventory search
**What this changes:**
- Above bug is now fixed. When typing anywhere other than the secondary inventory search, it will auto-focus the primary inventory search. Unless autofocus is disabled in the config, then it will function as usual.

Bugfix: search auto focus

---

server/services/inventoryService.lua

Fixed wrong handling of weapons taken from custom inventories causing players loosing their weapons on relog until next restart.
Problem was in charIds and propietaries not updated in server-side table UsersWeapons which has been leading to problem that on relog weapon wasn't added to players inventory on loading unless server is restarted.

Fix for weapons in custom inventories

---

client/client.lua
client/models/WeaponClass.lua
client/services/PickupsService.lua
client/services/UtilityService.lua

Saw a lot of places where `PlayerPedId()` native was being called in loops, this is better set to a field in the function so its only called once and will improve performance as its unlikely the PlayerPedId will change while these methods are running.
This also contains a fix to `Utils.useWeapon` as it wasn't using the `PlayerPedId()` native correctly.

chore: lower number of calls to the PlayerPedId

---

server/services/inventoryApiService.lua

Occurs when you have more than 1 stacked and set metadata for less than the stack size.
fix #209

fix: Wrong id when inserting new items_crafted

---

server/services/UtiliyService.lua
server/services/inventoryApiService.lua
server/services/inventoryService.lua
server/types/types.lua

> [!IMPORTANT]
>
I needed to register multiples callback for the same item inside of my script. Instead of just updating my version of vorp_inventory, I think it could be better to share this little update with everyone.
The more you add scripts to your server, the more there is chance for two scripts to register a callback for the exact same item, and create a conflict.
In other hand, scripts are actually limited by …

Allow scripts to register multiple callback on item use and unregister them

---

server/services/inventoryService.lua

> [!IMPORTANT]
>
There's an exploit in vorp inventory that allow users to spawn item in custom inventories.
Those changes should fix the exploit.
By using the NUI devtools users can do calls to the NUI registered callbacks manually, the call MoveToCustom is usually called by the UI after the prompt that ask for the quantity of the item to move, and the prompt usually check if you really have that quantity of item.
If …

Fixed an exploit that allowed people to spawn items

---

server/services/inventoryService.lua

this will fix the using wrong  and it will also fix the wrong player it was backwards  player giving was the player receiving the weapon
> [!IMPORTANT]
>
- when giving weapons with CustomDesc would always show the default it was trying to get `getDesc()` not `getCustomDesc()`
- also the info shown in the long was reversed the player getting the weapon was shown as giving it  
ignore the CustomDesc lol i told him to …

fix: useing wrong desc  needed to be useing `getCustomDesc`

---

client/controllers/NUIController.lua
client/services/NUIService.lua
html/js/config.js
html/js/secondaryInvScript.js

> [!IMPORTANT]
>
this the moment there is no way to know there is limit in game other then it just doing nothing at all 
adding this will let the player know there is a limit and you cant go above it 
I spent almost a hour trying to figure why i cant go above 200 and it hard coded to the JS  after speaking with outsider i found this out and just wanted to add a notify message to let players know  
I understand there is …

Chore: add notify when you try to exceed the max item transfer limit 

---

client/services/NUIService.lua
config/config.lua

Some servers may not want duel wielding enabled and it was not a config option.
This disables duel wielding and displays an error message if you attempt to equip another pistol.
This will allow people to disable duel wielding, it is enabled by default.
I have left duel wielding as enabled by default so it doesn't make any changes by default.

Add a config option to disable duel wielding. (Enabled by default)

---

shared/models/ItemClass.lua

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
Had an issue where items were not added because limit was set to -1 (we want weight limit to determine how much you can carry for most items)
Allow limit to be set to -1 and allow to ignore stack limit when adding item.
No real impact except more customization
Set item limit to -1 in DB for item 
Try to add -1 item 
All is triggered but item count does not update
After
Repeat but the item count will go up
- [X ] Tested with latest vorp scripts

allow setting negative numbers to ignore stack limit

---

client/services/NUIService.lua

> [!IMPORTANT]
>
- [ X ] Bug fix (non-breaking change which fixes an issue)
from time to time items would get extra  
```
T.cansell .. v.price .. "</span>
```
added to the metadata for description and would brake items from some scripts this should remove the extra being added 
- [ X ] Tested with latest vorp scripts
- [ X ] Tested with latest artifacts

Fix: NUIService StoreSynMenu extra metadata being added to item

---

server/services/inventoryService.lua

This merge adds 2 server-side events for the TakeFrom and MoveTo custom inventory actions.
We lack custom inventory control, additional events are always useful to use.
This does not require any special changes and will have no impact for users except developers.
Item is a table composed of "id", "name" and "amount".
```lua
AddEventHandler("vorp_inventory:Server:OnItemTakenFromCustomInventory", function(item, invId, source)
print("OnItemTakenFromCustomInventory", json.encode(item), invId, source)
end)
AddEventHandler("vorp_inventory:Server:OnItemMovedToCustomInventory", function(item, invId, source)
print("OnItemMovedToCustomInventory", json.encode(item), invId, source)
end)
```

Custom Inventory Server Events
